version: '3.7'

services:

  mosquitto:
    image: eclipse-mosquitto:1.6.13
    ports:
      - "1883:1883"
      - "1883:1883/udp"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data/mosquitto/data:/mosquitto/data 
      - ./data/mosquitto/log:/mosquitto/log
      - /etc/localtime:/etc/localtime:ro
    env_file: .env
    restart: unless-stopped

  nodered:
    image: nodered/node-red
    volumes:
      - ./data/nodered:/data 
      - /etc/localtime:/etc/localtime:ro
    env_file: .env
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.nodered-wize.entryPoints=web-secure
      - traefik.http.routers.nodered-wize.rule=Host(`nodered.wize.ranii.pro`)
      - traefik.http.routers.nodered-wize.tls.certresolver=default
    depends_on:
      - influxdb
      - mosquitto  

  influxdb:
    image: influxdb:alpine
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
      - ./data/influxdb:/var/lib/influxdb 
      - /etc/localtime:/etc/localtime:ro
    env_file: .env
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=*********
      - DOCKER_INFLUXDB_INIT_ORG=rancia
      - DOCKER_INFLUXDB_INIT_BUCKET=buqet
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.influxdb-wize.entryPoints=web-secure
      - traefik.http.routers.influxdb-wize.rule=Host(`influxdb.wize.ranii.pro`)
      - traefik.http.routers.influxdb-wize.tls.certresolver=default

  grafana:
    image: "grafana/grafana"
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./data/grafana:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,natel-discrete-panel,briangann-gauge-panel,vonage-status-panel,neocat-cal-heatmap-panel,ryantxu-ajax-panel,petrslavotinek-carpetplot-panel,grafana-piechart-panel
    env_file: .env
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana-wize.entryPoints=web-secure
      - traefik.http.services.grafana-wize.loadbalancer.server.port=3000
      - traefik.http.routers.grafana-wize.rule=Host(`grafana.wize.ranii.pro`)
      - traefik.http.routers.grafana-wize.tls.certresolver=default
    depends_on:
      - influxdb
